## NumPy

### start

imports

In [2]:
import sys
import numpy as np

## Basic Numpy Arrays

In [6]:
a= np.array([1,2,3,4])

In [7]:
b = np.array([0,.5,1,1.5,2])

In [8]:
a[0], a[1]

(1, 2)

In [9]:
a[:]

array([1, 2, 3, 4])

#### say you want another array that is a subset of b, containing 1st, 3rd and last element, we can use mult-indexing

In [10]:
b[[0,2,-1]]

array([0., 1., 2.])

## Array Types

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
b.dtype

dtype('float64')

#### As discussed we can select a differnt data type, to store the array more efficiently

In [16]:
c = np.array([1,2,3,4], dtype = np.int8)

In [17]:
c

array([1, 2, 3, 4], dtype=int8)

In [18]:
c.dtype

dtype('int8')

## Dimensions and shapes

In [20]:
A = np.array([
    [1,2,3],
    [3,5,6]
])

In [21]:
A.shape

(2, 3)

In [22]:
A.ndim

2

In [23]:
A.size

6

In [26]:
B = np.array([
    [[12,11,10],[9,8,7]],
    [[6,5,4],[3,2,1]]
])

In [27]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [28]:
B.shape

(2, 2, 3)

In [29]:
B.ndim

3

In [30]:
B.size

12

#### If the dimensions do not match, the code with revert back to standart python object!!!






#### Lets look at a square matrix

In [32]:
# square matrix
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

as expected

In [33]:
A[1]

array([4, 5, 6])

In [34]:
A[1][1]

5

#### Continuing the indexting is natural

In [35]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [40]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

#### Replacing elements

In [41]:
A[1] -=1

In [42]:
A

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [43]:
A[2][1] = 111

In [44]:
A

array([[  1,   2,   3],
       [  3,   4,   5],
       [  7, 111,   9]])

In [45]:
A[0] = np.array([0,0,0])

In [46]:
A

array([[  0,   0,   0],
       [  3,   4,   5],
       [  7, 111,   9]])

#### Summary statistics

In [47]:
A = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])

In [48]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
A.sum()

36

In [52]:
A.mean()

4.0

In [53]:
A.std()

2.581988897471611

In [54]:
A.mean(axis= 0)

array([3., 4., 5.])

In [55]:
A.sum(axis=0)

array([ 9, 12, 15])

## Broadcasting and Vectorized operations

In [8]:
a = np.arange(4)

In [9]:
a

array([0, 1, 2, 3])

operations work at an array level, every element in the array is effected

In [10]:
a + 10

array([10, 11, 12, 13])

This does not, by default, overide the array

In [11]:
a

array([0, 1, 2, 3])

as expected some list comprehension

In [12]:
l = [0,1,2,3]

In [15]:
bb = np.array([i * 10 for i in l])

In [16]:
bb

array([ 0, 10, 20, 30])

In [17]:
b = np.array([10,10,10,10])

In [18]:
b

array([10, 10, 10, 10])

In [19]:
b + bb

array([10, 20, 30, 40])

These proccesses are very memory efficient and fast

## Boolean arrays

(also called masks!)

In [20]:
a = np.arange(4)

In [21]:
a

array([0, 1, 2, 3])

In [22]:
a[[0,-1]]

array([0, 3])

selecting elements using boolean values

In [23]:
a[[True, False, False, True]]

array([0, 3])

not too complicated!

this is not very practical for large arrays
lets explore more!

In [25]:
a >= 2

array([False, False,  True,  True])

In [26]:
a[a >= 2]

array([2, 3])

this is effectivly saying give me an array where all the elements are elements from a that meet the specified conditions

In [27]:
a.mean()

1.5

In [28]:
a[a > a.mean()]

array([2, 3])

~ means 'not'

In [30]:
a[~(a > a.mean())]

array([0, 1])

give me the elements that are equal to 0 or 1

In [33]:
a[(a == 0) | (a == 1)]

array([0, 1])

give me the elements that are equal to 0 AND 1

In [34]:
a[(a == 0) & (a ==1)]

array([], dtype=int32)

give me the elements >= 1 and == 2 

In [35]:
a[(a >= 1) & (a == 2)]

array([2])

---

### Random integer 3 dimentional square matrix 

In [36]:
A = np.random.randint(100, size=(3, 3))

In [39]:
A

array([[19, 24, 39],
       [15, 65, 67],
       [53, 61, 99]])

In [44]:
B = [np.random.randint(100, size=(3,3)) for i in range(3)]

In [45]:
B

[array([[71, 33,  3],
        [37, 99, 49],
        [27, 68, 11]]),
 array([[28, 39, 89],
        [83, 47,  7],
        [68, 55, 28]]),
 array([[65, 80, 38],
        [26, 33, 90],
        [84, 62,  5]])]

lets look at using boolian values to find specific elements

In [48]:
A[np.array([
    [True, False, True],
    [False, True, True],
    [False, False, False]
])]

array([19, 39, 65, 67])

In [47]:
A[A > 30]

array([39, 65, 67, 53, 61, 99])

## Linear Algebra

Numpy has built in EFFICIENT operations, dot products, cross products etc....

In [99]:
A,C = np.array(np.random.randint(5, size=(3,3))),np.array(np.random.randint(5, size=(3,3)))

In [100]:
A,C

(array([[2, 4, 4],
        [0, 3, 4],
        [1, 1, 2]]),
 array([[4, 3, 4],
        [4, 3, 1],
        [3, 2, 2]]))

In [101]:
B = np.array(np.random.randint(5, size=(3,2)))

In [102]:
B

array([[0, 3],
       [0, 0],
       [4, 2]])

In [103]:
A.dot(B)

array([[16, 14],
       [16,  8],
       [ 8,  7]])

Cross product

In [104]:
A @ B

array([[16, 14],
       [16,  8],
       [ 8,  7]])

Transverse Matrix

In [105]:
B.T

array([[0, 0, 4],
       [3, 0, 2]])

transpose of B cross A

In [108]:
(B.T) @ A

array([[ 4,  4,  8],
       [ 8, 14, 16]])